version: '3'

services:
  web:
    image: node:18.18.2-alpine
    working_dir: /app
    volumes:
      - ./web:/app
    ports:
      - '3000:3000'
    command: >
      sh -c "
        yarn &&
        yarn start
      "

  cms:
    build:
      context: ./cms
    working_dir: /app
    volumes:
      - ./cms:/app
    ports:
      - 1337:1337
    environment:
      APP_KEYS: "Hw/GTizb/GKmedUOiitj5w==,vl+DYd36WGZkZsAsJHyoBw==,ed1dYJ/1RjYjn8udEXdGTw==,3a2g3pgIExLfMYsVYKi+iQ=="
      API_TOKEN_SALT: "1Cp7bA94NSN7DxOqkfQtdg=="
      ADMIN_JWT_SECRET: "1SVLxA3vdLYI/nOTQuiPpA=="
      TRANSFER_TOKEN_SALT: "1qGqWVk/GLIEO1W+dTSWVg=="
      JWT_SECRET: "6vXZUWshfJtc2LwcyahuIA=="
      DATABASE_CLIENT: "postgres"
      DATABASE_HOST: "db"
      DATABASE_PORT: "5432"
      DATABASE_NAME: "anitection"
      DATABASE_USERNAME: "user"
      DATABASE_PASSWORD: "password"
      DATABASE_SSL: "false"
    command: >
      sh -c "
        yarn &&
        yarn develop
      "

  db:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: anitection
    volumes:
      - db:/var/lib/postgresql/data

  bff:
    build:
      context: ./bff
    volumes:
      - ./bff:/go/src/app
    ports:
      - 8080:8080

  tbls:
    image: k1low/tbls
    working_dir: /work
    volumes:
      - ./:/work
    command: doc postgres://user:password@db:5432/anitection?sslmode=disable
    depends_on:
      - db

volumes:
  db:
