apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  namespace: anitection
data:
  mysql.cnf: |
    [mysqld]
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    default-authentication-plugin=mysql_native_password
    [client]
    default-character-set=utf8mb4
    [mysql]
    default-character-set=utf8mb4