---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
  namespace: anitection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms
  template:
    metadata:
      labels:
        app: cms
    spec:
      containers:
        - name: anitection-cms
          image: yumekiti/anitection-cms:latest
          ports:
            - containerPort: 1337
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: anitection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: anitection-db
          image: liupeng0518/mysql:5.7-arm64
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: database
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: password
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: mysql-configmap-volume
              mountPath: /etc/mysql/conf.d
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
        - name: mysql-configmap-volume
          configMap:
            name: anitection-mysql-configmap