---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
  namespace: anitection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms
  template:
    metadata:
      labels:
        app: cms
    spec:
      containers:
        - name: anitection-cms
          image: yumekiti/anitection-cms:0e243f0
          ports:
            - containerPort: 1337
          volumeMounts:
            - name: cms-persistent-storage
              mountPath: /app/public/uploads
      volumes:
        - name: cms-persistent-storage
          persistentVolumeClaim:
            claimName: cms-pv-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: anitection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: anitection-db
          image: postgres:16.0-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: anitection
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - name: db-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-persistent-storage
          persistentVolumeClaim:
            claimName: db-pv-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  namespace: anitection
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
        - name: anitection-bff
          image: yumekiti/anitection-bff:0e243f0
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: anitection
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: anitection-web
          image: yumekiti/anitection-web:60d235a
          ports:
            - containerPort: 80