---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
  namespace: anitection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms
  template:
    metadata:
      labels:
        app: cms
    spec:
      containers:
        - name: anitection-cms
          image: yumekiti/anitection-cms:latest
          ports:
            - containerPort: 1337
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: anitection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: anitection-db
          image: postgres:16.0-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: anitection
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim