---
apiVersion: v1
kind: Service
metadata:
  name: anitection-cms
  namespace: anitection
spec:
  selector:
    app: cms
  ports:
    - protocol: TCP
      port: 1337
      targetPort: 1337
  type: NodePort
