---
apiVersion: v1
kind: Service
metadata:
  name: cms
  namespace: anitection
spec:
  selector:
    app: cms
  ports:
    - protocol: TCP
      port: 1337
      targetPort: 1337
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: anitection
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: bff
  namespace: anitection
spec:
  selector:
    app: bff
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: anitection
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort